In [1]:
# Import dependencies
import pandas as pd

In [2]:
# Import data
ghg_shares_df = pd.read_csv("GHG FOOD system shares.csv")  
ghg_shares_df.head()

,Country_code_A3,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,Unnamed: 30,Unnamed: 31
0,ABW,0.094646,0.091967,0.094180,0.094255,0.095524,0.095044,0.108836,0.099570,0.125348,...,0.144212,0.142401,0.136197,0.140872,0.139143,0.148309,0.167106,0.167886,NaN,NaN
1,AFG,0.945286,0.956797,1.043980,1.052542,1.053925,1.049888,1.052223,1.050910,1.043679,...,0.632209,0.670341,0.703655,0.724509,0.720585,0.744354,0.694031,0.689524,NaN,NaN
2,AGO,0.260012,0.262357,0.265100,0.257833,0.249269,0.241900,0.263905,0.262938,0.280048,...,0.305326,0.367013,0.333412,0.366560,0.328805,0.372303,0.380338,0.365586,NaN,NaN
3,AIA,0.315645,0.294148,0.293971,0.265715,0.243296,0.229146,0.230939,0.249530,0.254434,...,0.218826,0.219834,0.215168,0.216224,0.216742,0.216764,0.215284,0.217982,NaN,NaN
4,AIR,0.005050,0.005049,0.005048,0.005048,0.005047,0.005047,0.005047,0.005047,0.005047,...,0.005047,0.005047,0.005047,0.005047,0.005047,0.005047,0.005046,0.005046,NaN,NaN

In [9]:
# Find null values
for column in ghg_shares_df.columns:
    print(f"Column {column} has {ghg_shares_df[column].isnull().sum()} null values")

Column Country_code_A3 has 0 null values
Column 1990 has 0 null values
Column 1991 has 0 null values
Column 1992 has 0 null values
Column 1993 has 0 null values
Column 1994 has 0 null values
Column 1995 has 0 null values
Column 1996 has 0 null values
Column 1997 has 0 null values
Column 1998 has 0 null values
Column 1999 has 0 null values
Column 2000 has 0 null values
Column 2001 has 0 null values
Column 2002 has 0 null values
Column 2003 has 0 null values
Column 2004 has 0 null values
Column 2005 has 0 null values
Column 2006 has 0 null values
Column 2007 has 0 null values
Column 2008 has 0 null values
Column 2009 has 0 null values
Column 2010 has 0 null values
Column 2011 has 0 null values
Column 2012 has 0 null values
Column 2013 has 0 null values
Column 2014 has 0 null values
Column 2015 has 0 null values
Column 2016 has 0 null values
Column 2017 has 0 null values
Column 2018 has 0 null values

In [5]:
ghg_shares_df

,Country_code_A3,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2011,2012,2013,2014,2015,2016,2017,2018,Unnamed: 30,Unnamed: 31
0,ABW,0.094646,0.091967,0.094180,0.094255,0.095524,0.095044,0.108836,0.099570,0.125348,...,0.144212,0.142401,0.136197,0.140872,0.139143,0.148309,0.167106,0.167886,NaN,NaN
1,AFG,0.945286,0.956797,1.043980,1.052542,1.053925,1.049888,1.052223,1.050910,1.043679,...,0.632209,0.670341,0.703655,0.724509,0.720585,0.744354,0.694031,0.689524,NaN,NaN
2,AGO,0.260012,0.262357,0.265100,0.257833,0.249269,0.241900,0.263905,0.262938,0.280048,...,0.305326,0.367013,0.333412,0.366560,0.328805,0.372303,0.380338,0.365586,NaN,NaN
3,AIA,0.315645,0.294148,0.293971,0.265715,0.243296,0.229146,0.230939,0.249530,0.254434,...,0.218826,0.219834,0.215168,0.216224,0.216742,0.216764,0.215284,0.217982,NaN,NaN
4,AIR,0.005050,0.005049,0.005048,0.005048,0.005047,0.005047,0.005047,0.005047,0.005047,...,0.005047,0.005047,0.005047,0.005047,0.005047,0.005047,0.005046,0.005046,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,WSM,0.719805,0.718852,0.731014,0.717215,0.702275,0.703758,0.700857,0.696979,0.691496,...,0.606658,0.619439,0.624898,0.625495,0.554799,0.576177,0.536240,0.530347,NaN,NaN
219,YEM,0.432143,0.397407,0.396544,0.408579,0.387913,0.401492,0.409007,0.408322,0.414954,...,0.368481,0.384124,0.356303,0.372270,0.506081,0.561579,0.574033,0.602037,NaN,NaN
220,ZAF,0.189088,0.192775,0.194168,0.191612,0.193006,0.188438,0.185872,0.181455,0.179366,...,0.184501,0.180893,0.180794,0.177758,0.183916,0.183682,0.187838,0.188581,NaN,NaN
221,ZMB,0.102467,0.102920,0.102894,0.102603,0.101866,0.101122,0.092030,0.102827,0.098855,...,0.141182,0.139639,0.137452,0.146296,0.143978,0.135665,0.156706,0.158798,NaN,NaN
222,ZWE,0.610293,0.569949,0.574652,0.569662,0.594138,0.597988,0.636142,0.645170,0.646976,...,0.670255,0.660512,0.658300,0.631873,0.638098,0.234139,0.235305,0.235726,NaN,NaN

In [7]:
# Remove Column 30 and 31
ghg_shares_df.drop(columns=["Unnamed: 30"], inplace=True)
ghg_shares_df.drop(columns=["Unnamed: 31"], inplace=True)

In [8]:
ghg_shares_df.dtypes

Country_code_A3     object
1990               float64
1991               float64
1992               float64
1993               float64
1994               float64
1995               float64
1996               float64
1997               float64
1998               float64
1999               float64
2000               float64
2001               float64
2002               float64
2003               float64
2004               float64
2005               float64
2006               float64
2007               float64
2008               float64
2009               float64
2010               float64
2011               float64
2012               float64
2013               float64
2014               float64
2015               float64
2016               float64
2017               float64
2018               float64
dtype: object

In [10]:
# Change column name
ghg_shares_df.rename(columns={"Country_code_A3": "Country Code"})

,Country Code,1990,1991,1992,1993,1994,1995,1996,1997,1998,...,2009,2010,2011,2012,2013,2014,2015,2016,2017,2018
0,ABW,0.094646,0.091967,0.094180,0.094255,0.095524,0.095044,0.108836,0.099570,0.125348,...,0.137071,0.132087,0.144212,0.142401,0.136197,0.140872,0.139143,0.148309,0.167106,0.167886
1,AFG,0.945286,0.956797,1.043980,1.052542,1.053925,1.049888,1.052223,1.050910,1.043679,...,0.744965,0.718972,0.632209,0.670341,0.703655,0.724509,0.720585,0.744354,0.694031,0.689524
2,AGO,0.260012,0.262357,0.265100,0.257833,0.249269,0.241900,0.263905,0.262938,0.280048,...,0.368343,0.358507,0.305326,0.367013,0.333412,0.366560,0.328805,0.372303,0.380338,0.365586
3,AIA,0.315645,0.294148,0.293971,0.265715,0.243296,0.229146,0.230939,0.249530,0.254434,...,0.237673,0.224758,0.218826,0.219834,0.215168,0.216224,0.216742,0.216764,0.215284,0.217982
4,AIR,0.005050,0.005049,0.005048,0.005048,0.005047,0.005047,0.005047,0.005047,0.005047,...,0.005047,0.005047,0.005047,0.005047,0.005047,0.005047,0.005047,0.005047,0.005046,0.005046
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
218,WSM,0.719805,0.718852,0.731014,0.717215,0.702275,0.703758,0.700857,0.696979,0.691496,...,0.651569,0.644026,0.606658,0.619439,0.624898,0.625495,0.554799,0.576177,0.536240,0.530347
219,YEM,0.432143,0.397407,0.396544,0.408579,0.387913,0.401492,0.409007,0.408322,0.414954,...,0.350675,0.347959,0.368481,0.384124,0.356303,0.372270,0.506081,0.561579,0.574033,0.602037
220,ZAF,0.189088,0.192775,0.194168,0.191612,0.193006,0.188438,0.185872,0.181455,0.179366,...,0.178837,0.175907,0.184501,0.180893,0.180794,0.177758,0.183916,0.183682,0.187838,0.188581
221,ZMB,0.102467,0.102920,0.102894,0.102603,0.101866,0.101122,0.092030,0.102827,0.098855,...,0.115844,0.111326,0.141182,0.139639,0.137452,0.146296,0.143978,0.135665,0.156706,0.158798
222,ZWE,0.610293,0.569949,0.574652,0.569662,0.594138,0.597988,0.636142,0.645170,0.646976,...,0.766087,0.706355,0.670255,0.660512,0.658300,0.631873,0.638098,0.234139,0.235305,0.235726